controller/urls.py
from django.contrib import admin
from django.urls import path, include

from api.endpoints import my_api

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('oca.urls')),
    path("api/", my_api.urls),
]

oca/urls.py
from django.urls import path

from oca import views

app_name = 'oca'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pilot_cid>/', views.pilot, name='pilot'),
    path('<int:pilot_cid>/report', views.report, name='report'),
    path('<int:pilot_cid>/clearence', views.clearance, name='clearance'),
]

api/models.py
from django.db import models

# Create your models here.
from models.atc import ATC


class Report(models.Model):
    belongs_to = models.ForeignKey('Pilot', on_delete=models.CASCADE)
    created_by = models.ForeignKey('Controller', on_delete=models.CASCADE)
    current_position = models.CharField(max_length=30)
    current_position_time = models.CharField(max_length=30)
    flight_level = models.PositiveSmallIntegerField()
    mach_number = models.PositiveSmallIntegerField()
    next_position = models.CharField(max_length=30)
    next_position_time = models.CharField(max_length=30)
    thereafter_position = models.CharField(max_length=30)
    selcal = models.CharField(max_length=4)
    fans_a = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.belongs_to.callsign} - {self.current_position} -> {self.next_position}"


class Controller(models.Model):
    cid = models.CharField(max_length=30, unique=True)
    callsign = models.CharField(max_length=30)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.callsign} - {self.cid}"

    def live_data(self) -> ATC:
        pass

    @property
    def facility(self) -> str:
        return "LPPO_FSS"


class Pilot(models.Model):
    cid = models.CharField(max_length=30, unique=True)
    callsign = models.CharField(max_length=30)
    assumed_by = models.ForeignKey('Controller', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.callsign} - {self.cid}"

models/atc.py
from typing import Optional, List

from pydantic import BaseModel, validator


class ATC(BaseModel):
    cid: int
    name: str
    callsign: str
    frequency: float
    facility: int
    rating: int
    server: str
    visual_range: int
    text_atis: Optional[List]
    last_updated: str
    logon_time: str

    @validator('text_atis')
    def text_atis_exists(cls, v):
        if v is None:
            return []
        return v

models/exceptions.py
class ApiError(Exception):
    def __init__(self, message: str):
        super().__init__(f'[API] {str(message)}')


class DataNotFound(ApiError):
    def __init__(self, location: str, error: str):
        super().__init__(f'Could not find requested data\nError: {str(error)}\nIn: {str(location)}')

models/flight_plan.py
from pydantic import BaseModel


class FlightPlan(BaseModel):
    flight_rules: str
    aircraft: str
    aircraft_faa: str
    aircraft_short: str
    departure: str
    arrival: str
    alternate: str
    cruise_tas: int
    altitude: str
    deptime: int
    enroute_time: int
    fuel_time: int
    remarks: str
    route: str
    revision_id: int
    assigned_transponder: str

    def selcal(self) -> str:
        """Returns a string with the SELCAL in uppercase from remarks"""
        pass

models/pilot.py
from typing import Optional

from pydantic import BaseModel, validator

from models.flight_plan import FlightPlan


class Pilot(BaseModel):
    cid: int
    name: str
    callsign: str
    server: str
    pilot_rating: int
    latitude: float
    longitude: float
    altitude: int
    groundspeed: int
    transponder: int
    heading: int
    qnh_i_hg: float
    qnh_mb: int
    flight_plan: Optional[FlightPlan]
    logon_time: str
    last_updated: str

models/position_report.py
from datetime import datetime

from pydantic.main import BaseModel

from models.route_point import RoutePoint


class PositionReport(BaseModel):
    call_sign: str
    current_position: str
    current_position_time: str
    flight_level: int = 300
    mach_number: int = 82
    next_position: str
    next_position_time: str
    thereafter_position: str
    selcal: str = 'ABCD'
    fans_a: bool = False

    @property
    def route_point_current_position(self) -> RoutePoint:
        return RoutePoint(self.current_position)

    @property
    def route_point_next_position(self) -> RoutePoint:
        return RoutePoint(self.next_position)

    @property
    def datetime_current_position_time(self) -> datetime:
        """
        current_position_time is a string with format HH:MM (example 12:12)
        :return: default day, month, year, second correspondent hour and minute
        :rtype: datetime
        """
        return datetime.strptime(self.current_position_time, "%H:%M")

    @property
    def datetime_next_position_time(self) -> datetime:
        """
        next_position_time is a string with format HH:MM (example 12:12)
        :return: default day, month, year, second correspondent hour and minute
        :rtype: datetime
        """
        next_position_time = datetime.strptime(self.next_position_time, "%H:%M")
        if next_position_time < self.datetime_current_position_time:
            return next_position_time.replace(day=2)
        return next_position_time

models/route_point.py
import re
from dataclasses import dataclass

from pydantic import BaseModel, validator


@dataclass
class RegexPoint:
    latitude: str
    horizontal_hemisphere: str
    longitude: str
    flag_position: str
    short_longitude: str
    vertical_hemisphere: str

    def __post_init__(self):
        assert 0 <= int(self.latitude) <= 90
        assert 0 <= int(self.longitude) <= 180

    def quadrant(self):
        if self.horizontal_hemisphere == 'N' and self.vertical_hemisphere == 'W':
            return 'N'
        if self.horizontal_hemisphere == 'N' and self.vertical_hemisphere == 'E':
            return 'E'
        if self.horizontal_hemisphere == 'S' and self.vertical_hemisphere == 'W':
            return 'W'
        if self.horizontal_hemisphere == 'S' and self.vertical_hemisphere == 'E':
            return 'S'


class RoutePoint(BaseModel):
    identifier: str = ''

    @validator('identifier')
    def format(cls, v):
        v = v.replace('+', '')
        v = v.upper()
        v = v.split('/')[0]
        return v.strip()

    @validator('identifier')
    def convert_to_arinc(cls, v):
        match = re.match(r"(\d{2})([NS])((\d)(\d{2}))([WE])", v)
        if not match:
            return v
        try:
            point = RegexPoint(*match.groups())
        except AssertionError:
            return v
        if not int(point.flag_position):
            return f"{point.latitude}{point.short_longitude}{point.quadrant()}"
        return f"{point.latitude}{point.quadrant()}{point.short_longitude}"

oca/models.py
from django.db import models

# Create your models here.

oca/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'layout.html', {"controller_cid": 1438868})


def pilot(request, pilot_cid: int):
    return render(request, 'pilot-profile.html', {"pilot_cid": pilot_cid, "controller_cid": 1438868})


def report(request, pilot_cid: int):
    return render(request, 'position-report.html', {"pilot_cid": pilot_cid, "controller_cid": 1438868})


def clearance(request, pilot_cid: int):
    return render(request, 'oceanic-clearance.html', {"pilot_cid": pilot_cid, "controller_cid": 1438868})

oca/templates/components/assume-release.html
<div id="assume-release-button" class="d-grid gap-2"></div>
<script>
    function redirectToPilotProfile() {
        window.location.href = "../{{ pilot_cid }}";
    }

    function assumeButton() {
        document.getElementById('assume-release-button').innerHTML = `<button class="btn btn btn-outline-success" onclick="assumePilot()" type="button">Assume</button>`;
    }

    function releaseButton() {
        document.getElementById('assume-release-button').innerHTML = `<button class="btn btn btn-outline-danger" onclick="releasePilot()" type="button">Release</button>`;
    }

    fetch(`../api/pilots/{{ pilot_cid }}`)
        .then(res => res.json())
        .then(pilot => (pilot.assumed_by.cid === {{ controller_cid }} ? releaseButton() : assumeButton()))
        .catch(assumeButton())

    function assumePilot() {
        fetch(`../api/pilots/{{ pilot_cid }}?controller_cid={{ controller_cid }}`, {
            method: 'POST',
        })
            .then(res => res.json())
            .then(response => (response.success === true ? redirectToPilotProfile() : console.log(response)))
    }

    function releasePilot() {
        fetch(`../api/pilots/{{ pilot_cid }}?controller_cid={{ controller_cid }}`, {
            method: 'DELETE',
        })
            .then(res => res.json())
            .then(response => (response.success === true ? redirectToPilotProfile() : console.log(response)))
    }
</script>

oca/templates/components/assumed.html
<div class="card">
    <div class=" card-body text-center">
        <div class="card-header border-dark">Assumed Aircraft</div>
        <div class="list-group" id="aircraftAssumedPlaceholder"></div>
    </div>
</div>
<script>
    let my_callsign = "LPPO_FSS"

    fetch(`../api/pilots`)
        .then(response => {
            return response.json();
        })
        .then(json => {
            const html = json.map(pilot => {
                return `<a href="../${pilot.cid}" class="list-group-item list-group-item-action">
                            ${pilot.callsign}
                            <span class="mx-1 badge ${pilot.assumed_by.callsign === my_callsign ? 'bg-success' : 'bg-secondary'}">
                                ${pilot.assumed_by.callsign}
                            </span>
                        </a>`;
            }).join("");
            document.getElementById('aircraftAssumedPlaceholder').innerHTML = html;
        })
</script>

oca/templates/components/breadcrumb.html
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'oca:pilot' pilot_cid %}">{{ pilot_cid }}</a></li>
    </ol>
</nav>

oca/templates/components/handoff.html
<div id="handoff-button" class="d-grid gap-2">
</div>
<script>
    function disabledHandOffButton() {
        document.getElementById('handoff-button').innerHTML = `<button class="btn btn btn-warning" type="button" disabled>Hand Off</button>`
    }

    function handOffButton() {
        document.getElementById('handoff-button').innerHTML = `<button class="btn btn btn-warning" onclick="handoffPilot()" type="button">Hand Off</button>`
    }

    fetch(`../api/controllers`)
        .then(res => res.json())
        .then(controllers => {
            controllers.length > 1 ? handOffButton() : disabledHandOffButton()
        })
        .catch(error => disabledHandOffButton())

    function redirectToPilotProfile() {
        window.location.href = "../{{ pilot_cid }}";
    }

    function handoffPilot() {
        fetch(`../api/pilots/{{ pilot_cid }}?controller_cid={{ controller_cid }}`, {
            method: 'POST',
        })
            .then(res => res.json())
            .then(response => (response.success === true ? redirectToPilotProfile() : console.log("ALGO DE ERRADO ACONTECEU assumePilot(handoffrealease.html)")))
    }
</script>

oca/templates/components/last-position-reports.html
<div class="card">
    <div class="card-header">Last Position Reports</div>
    <div id="my-table-body" class="table-responsive">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Position</th>
                <th scope="col">Time</th>
                <th scope="col">Flight Level</th>
                <th scope="col">Mach</th>
                <th scope="col">Estimate</th>
                <th scope="col">Time</th>
                <th scope="col">Next</th>
                <th scope="col">SELCAL</th>
                <th scope="col">FANS A</th>
                <th scope="col">Created By</th>
            </tr>
            </thead>
            <tbody id="positionReportsPlaceholder">
            </tbody>
        </table>
    </div>
</div>
<script>

    function posReportHistory(key, posReport) {
        var wrapper = document.createElement('tr')
        wrapper.innerHTML =
            '<th scope="row">' + key + '</th>' +
            '<td><span class="badge bg-dark">' + posReport.current_position + '</span></td>' +
            '<td>' + posReport.current_position_time + '</span></td>' +
            '<td><span class="badge bg-dark">' + posReport.flight_level + '</span></td>' +
            '<td><span class="badge bg-dark">' + posReport.mach_number + '</span></td>' +
            '<td><span class="badge bg-dark">' + posReport.next_position + '</span></td>' +
            '<td>' + posReport.next_position_time + '</td>' +
            '<td><span class="badge bg-dark">' + posReport.thereafter_position + '</span></td>' +
            '<td><span class="badge bg-dark">' + posReport.selcal + '</span></td>' +
            '<td>' + posReport.fans_a + '</td>' +
            '<td><span class="badge bg-dark">' + posReport.created_by.callsign + '</span></td>'
        document.getElementById('positionReportsPlaceholder').append(wrapper);
    }

    fetch(`../api/reports/{{ pilot_cid }}`)
        .then(response => {
            return response.json();
        })
        .then(json => {
            Object.entries(json).reverse().forEach(([key, value]) => {
                posReportHistory(key, value)
            });
        }).catch(error => {
        document.getElementById('my-table-body').innerHTML = ` <div class="alert mx-3 my-3 alert-secondary" role="alert">No reports for this pilot...</div>`;
    })
</script>

oca/templates/components/pilot-info.html
<div class="content-section">
    <div id="pilot-content" class="row text-center">
        <div id="callsign"></div>
        <h4>
            <small id="departure"></small> → <small id="arrival"></small>
        </h4>
        <small id="pilot-name"></small>
    </div>
</div>

<script>
    let assumed = true;

    fetch(`../api/live/pilots/{{ pilot_cid }}`)
        .then(res => res.json())
        .then(live_pilot => {
            fetch(`../api/pilots/{{ pilot_cid }}`)
                .then(res => res.json())
                .then(pilot => (document.getElementById('callsign').innerHTML = `<h2><span class="badge rounded-pill ${pilot.assumed_by.cid === {{ controller_cid }} ? 'bg-success' : 'bg-secondary'}">${live_pilot.callsign}</span></h2>`))
                .catch(error => (document.getElementById('callsign').innerHTML = `<h2><span class="badge rounded-pill bg-secondary">${live_pilot.callsign}</span></h2>`))

            document.getElementById('departure').innerHTML = live_pilot.flight_plan.departure;
            document.getElementById('arrival').innerHTML = live_pilot.flight_plan.arrival;
            document.getElementById('pilot-name').innerHTML = live_pilot.name;
        }).catch(error => {
        document.getElementById('pilot-content').innerHTML = `<div class="alert alert-danger" role="alert">This pilot appears to be offline</div>
        `;
    })

</script>

oca/templates/components/select-aircraft.html
<div class="my-3 mx-3">
    <p class="text-center"><b>SELECT AIRCRAFT:</b></p>
    <select aria-label="Default select example" class="form-select" id="aircraft-select"
            onchange="window.location.href = `../${value}`;"></select>
</div>
<script>
    fetch(`../api/live/pilots`)
        .then(response => {
            return response.json();
        })
        .then(json => {
            json.sort(function (a, b) {
                a = a.callsign.toLowerCase();
                b = b.callsign.toLowerCase();
                return a < b ? -1 : a > b ? 1 : 0;
            });
            const html = json.map(pilot => {
                return `<option class="text-center" value="${pilot.cid}">${pilot.callsign}</option>`;
            }).join("");
            document.getElementById('aircraft-select').innerHTML = `<option selected></option> ${html}`;
        })
</script>

oca/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


    {% load static %}
    <link href="{% static 'oca/favicon.ico' %}" rel="shortcut icon">
    <link rel="stylesheet" type="text/css" href="{% static 'oca/style.css' %}">

    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>OCA Web System</title>
    {% endif %}
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="/">OCA Web System</a>
        </div>
    </nav>
</header>
<main class="container" role="main">
    <div class="mx-auto">
        <div class="card gx-5 mb-3">
            {% include 'components/select-aircraft.html' %}
        </div>
    </div>
    <div class="row">
        <div class="col">
            {% block content %}{% endblock %}
        </div>
        <div class="col-auto">
            {% include 'components/assumed.html' %}
        </div>
    </div>
</main>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>


{% block script %}{% endblock %}
</body>
</html>

oca/templates/oceanic-clearance.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <div class="form-group d-grid gap-2">
        {% include 'components/breadcrumb.html' %}
        {% with call_sign=call_sign %}{% include 'components/pilot-info.html' %}{% endwith %}
    </div>
</div>
{% endblock content %}

oca/templates/pilot-profile.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        {% include 'components/breadcrumb.html' %}
        {% include 'components/pilot-info.html' %}
        <div class="d-grid gap-2 col-6 mx-auto">
            <button onclick="window.location.href = `{% url 'oca:report' pilot_cid %}`" class="btn btn-primary" type="button">Position Report
            </button>
            <button onclick="window.location.href = `{% url 'oca:clearance' pilot_cid %}`" class="btn btn-primary"
                    type="button">Oceanic Clearance
            </button>
            {% include "components/handoff.html" %}
            {% include "components/assume-release.html" %}
        </div>
        <div>

        </div>
    </div>
    {% include 'components/last-position-reports.html' %}
{% endblock content %}

oca/templates/position-report.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form action="../api/reports/{{ pilot_cid }}?controller_cid={{ controller_cid }}" enctype="multipart/form-data"
              method="POST">
            <fieldset class="form-group">
                {% include 'components/breadcrumb.html' %}
                {% include 'components/pilot-info.html' %}
                <div class="row mb-3">
                    <div class="col">
                        <label class="form-label" for="current_position">Position</label>
                        <select class="form-select" id="current_position" name="current_position"></select>
                    </div>
                    <div class="col">
                        <label class="form-label">Time</label>
                        <input class="form-control" id="current_position_time" name="current_position_time" required
                               type="time">
                    </div>
                    <div class="col">
                        <label class="form-label">Flight Level</label>
                        <div class="input-group mb-3">
                            <span class="input-group-text">FL</span>
                            <input class="form-control" id="flight_level" maxlength="3" name="flight_level"
                                   placeholder="XXX"
                                   required type="text">
                        </div>
                    </div>
                    <div class="col">
                        <label class="form-label">Mach</label>
                        <div class="input-group mb-3">
                            <input class="form-control" id="mach_number" maxlength="3" minlength="1" name="mach_number"
                                   placeholder="XXX" required type="text">
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col">
                        <label class="form-label" for="next_position">Estimate</label>
                        <select class="form-select" id="next_position" name="next_position"></select>
                    </div>
                    <div class="col">
                        <label class="form-label">Time</label>
                        <input class="form-control" id="next_position_time" name="next_position_time" required
                               type="time">
                    </div>
                </div>
                <div class="col form-group mb-3">
                    <label class="form-label" for="thereafter_position">Next</label>
                    <select class="form-select" id="thereafter_position" name="thereafter_position"></select>
                </div>
                <div class="col form-group mb-3">
                    <label class="form-label">SELCAL</label>
                    <input class="form-control" id="selcal" maxlength="4" minlength="4" name="selcal" placeholder="XXXX"
                           type="text">
                </div>
                <div class="form-check">
                    <input class="form-check-input" id="fansa" name="fansa" type="checkbox" value="true">
                    <label class="form-check-label" for="fansa">FANS A</label>
                </div>

            </fieldset>
            <div class="my-3 form-group d-grid gap-2">
                <button class="btn btn btn-outline-danger" onclick="testConflict()" type="button">Test Conflict</button>
                <button class="btn btn btn-success" id="save" type="submit">Save</button>
            </div>
        </form>
    </div>
{% endblock content %}

{% block script %}
    <script>
        function testConflict() {
            fetch(``)
                .then(response => {
                    return response.json();
                })
                .then(json => {
                    console.log(json)
                })
        }

            fetch(`../api/live/pilots/${ {{ pilot_cid }} }/route`)
                .then(response => {
                    return response.json();
                })
                .then(json => {
                    const html = json.map(route_point => {
                        return `<option value="${route_point}">${route_point}</option>`;
                    }).join("");
                    document.getElementById('current_position').innerHTML = html;
                    document.getElementById('next_position').innerHTML = html;
                    document.getElementById('thereafter_position').innerHTML = html;
                })
    </script>
{% endblock script %}